version: '2.0'
services:
  server:
    build: .
    image: 18731-policy-server
    volumes:
      - ./:/policyserver
    ports:
      - 8000:8000
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379
